# Generated by Django 4.1.5 on 2023-01-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="estadoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registroTiempo", models.CharField(default="", max_length=32)),
                ("registroInformacion", models.CharField(default="", max_length=16)),
            ],
        ),
    ]
