# Generated by Django 4.1.5 on 2023-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotVehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadovehiculo',
            name='registroInformacion',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='estadovehiculo',
            name='registroTiempo',
            field=models.DateTimeField(),
        ),
    ]
